modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/Electrisoma/bloodisfuel/issues/"
license="MIT"

[[mods]]
modId="bloodisfuel"
version="1.2.0"
displayName="Blood is Fuel"
authors="Me!"
description='''
This is an example description! Tell everyone what your mod is about!
'''
logoFile="icon.png"

[[dependencies.bloodisfuel]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.bloodisfuel]]
modId="create"
mandatory=true
versionRange="[6.0.2,6.1.0)"
ordering="NONE"
side="BOTH"